name: Deploy Landing Page

on:
    push:
        branches:
            - "main"
        paths:
            - "apps/landing-page/**"

env:
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: "https://registry.npmjs.org"

            - run: npm ci

            - run: npm run build

            - run: npm run deploy
              working-directory: ./apps/landing-page
